### ISSUE TITLE
Unable to open Mopidy

### ISSUE THREAD

**Issue by lukasheinz92** [IVData/dockerfiles#29]
Hello, after running a fresh mopidy container I am not able to open it in my web browser (using WSL Ubuntu). Ports are set correctly (I also use an older image of mopidy in my RPI and it is working there correctly). The container seems to be running.

**Comment by hamishfagg** [comment]
Hey,

I can see why this is happening, but I'll need to make a fix tonight.
In the mean time, if you run the container like this it should fix your issue:

`docker run <all your options> --entrypoint /bin/sh ivdata/mopidy -c "mkdir -p /home/mopidy/.config/mopidy && /usr/local/bin/modipy.sh"`

(you will need to delete your existing container and run a fresh one like this the first time)

**Comment by hamishfagg** [comment]
I've pushed an update to dockerhub. Try it out and let me know if it doesn't solve your issue.

**Comment by lukasheinz92** [comment]
Hello,
it is not working at all, please see the log:

```
ERROR    2022-08-05 08:11:48,511 [1:MainThread] mopidy.commands
  Got un-handled exception from M3UBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
      
d
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 413, in start_backends
    config=config, audio=audio
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 86, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/m3u/backend.py", line 13, in __init__
    self.playlists = playlists.M3UPlaylistsProvider(self, config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/m3u/playlists.py", line 53, in __init__
    self._playlists_dir = Extension.get_data_dir(config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/ext.py", line 122, in get_data_dir
    path.get_or_create_dir(data_dir_path)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/internal/path.py", line 23, in get_or_create_dir
    dir_path.mkdir(mode=0o755, parents=True)
  File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/mopidy/.config/mopidy/m3u'
WARNING  2022-08-05 08:11:48,520 [1:MainThread] mopidy_local.storage
  Local media dir /media/music does not exist or we lack permissions to the directory or one of its parents
INFO     2022-08-05 08:11:48,520 [1:MainThread] mopidy.internal.path
  Creating dir file:///home/mopidy/.config/mopidy/local
ERROR    2022-08-05 08:11:48,521 [1:MainThread] mopidy.commands
  Got un-handled exception from LocalBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
      
d
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 413, in start_backends
    config=config, audio=audio
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 86, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_local/actor.py", line 25, in __init__
    self.library = LocalLibraryProvider(backend=self, config=config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_local/library.py", line 36, in __init__
    self._data_dir = Extension.get_data_dir(config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/ext.py", line 122, in get_data_dir
    path.get_or_create_dir(data_dir_path)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/internal/path.py", line 23, in get_or_create_dir
    dir_path.mkdir(mode=0o755, parents=True)
  File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/mopidy/.config/mopidy/local'
INFO     2022-08-05 08:11:48,522 [1:MainThread] mopidy.commands
  Starting Mopidy core
INFO     2022-08-05 08:11:48,522 [1:Audio-2] mopidy.audio.actor
  Audio output set to "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapcast/snapfifo"
INFO     2022-08-05 08:11:48,527 [1:MainThread] mopidy.commands
  Starting Mopidy frontends: HttpFrontend, MpdFrontend, IrisFrontend
INFO     2022-08-05 08:11:48,528 [1:HttpFrontend-7] mopidy.http.actor
  HTTP server running at [::]:6680
INFO     2022-08-05 08:11:48,529 [1:MainThread] mopidy_mpd.actor
  MPD server running at [::]:6600
INFO     2022-08-05 08:11:48,530 [1:HttpServer] mopidy.internal.path
  Creating dir file:///home/mopidy/.config/mopidy/local
ERROR    2022-08-05 08:11:48,531 [1:HttpServer] mopidy.http.actor
  Loading local failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/http/actor.py", line 159, in _get_app_request_handlers
    request_handlers = app["factory"](self.config, self.core)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_local/__init__.py", line 52, in webapp
    image_dir = self.get_image_dir(config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_local/__init__.py", line 68, in get_image_dir
    return cls.get_data_subdir(config, "images")
  File "/usr/local/lib/python3.7/dist-packages/mopidy_local/__init__.py", line 61, in get_data_subdir
    data_dir = cls.get_data_dir(config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/ext.py", line 122, in get_data_dir
    path.get_or_create_dir(data_dir_path)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/internal/path.py", line 23, in get_or_create_dir
    dir_path.mkdir(mode=0o755, parents=True)
  File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/mopidy/.config/mopidy/local'
INFO     2022-08-05 08:11:48,531 [1:IrisFrontend-9] mopidy_iris.core
  Starting Iris 3.64.0
INFO     2022-08-05 08:11:48,531 [1:MainThread] mopidy.commands
  Starting GLib mainloop
INFO     2022-08-05 08:11:48,533 [1:IrisFrontend-9] mopidy.internal.path
  Creating dir file:///home/mopidy/.config/mopidy/iris
ERROR    2022-08-05 08:11:48,533 [1:IrisFrontend-9] pykka
  Unhandled exception in IrisFrontend (urn:uuid:b8713861-01d5-4e9e-91e0-7c5df5ccd876):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 179, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/frontend.py", line 20, in on_start
    iris.start()
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/core.py", line 60, in start
    self.data["commands"] = self.load_from_file("commands")
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/core.py", line 77, in load_from_file
    file_path = Extension.get_data_dir(self.config) / ("%s.pkl" % name)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/ext.py", line 122, in get_data_dir
    path.get_or_create_dir(data_dir_path)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/internal/path.py", line 23, in get_or_create_dir
    dir_path.mkdir(mode=0o755, parents=True)
  File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/mopidy/.config/mopidy/iris'
INFO     2022-08-05 08:11:48,534 [1:HttpServer] mopidy.internal.path
  Creating dir file:///home/mopidy/.config/mopidy/http
```

**Comment by hamishfagg** [comment]
Yep, my mistake. I've just updated the container again and it's working for me now.

If you are mounting a local folder for mopidy config you may need to delete / move / change permissions on this local folder before it will work - the old container was creating files/folders in there as root which was the cause of the permissions errors.

**Comment by lukasheinz92** [comment]
It is working now, thank you!
